/**
 * \file rendering/render_defines.hpp
*/
#ifndef YOCKCRAFT_RENDER_DEFINES_HPP
#define YOCKCRAFT_RENDER_DEFINES_HPP

namespace yockcraft {

  enum BufferUsage {
    STATIC_DRAW = GL_STATIC_DRAW ,
    DYNAMIC_DRAW = GL_DYNAMIC_DRAW ,
    STREAM_DRAW = GL_STREAM_DRAW ,
  };
  
  enum BufferType {
    ARRAY_BUFFER = GL_ARRAY_BUFFER ,
    ELEMENT_ARRAY_BUFFER = GL_ELEMENT_ARRAY_BUFFER ,
  };

  enum DrawMode {
    TRIANGLES = GL_TRIANGLES ,
    TRIANGLE_STRIP = GL_TRIANGLE_STRIP ,
    TRIANGLE_FAN = GL_TRIANGLE_FAN ,
    LINES = GL_LINES ,
    LINE_STRIP = GL_LINE_STRIP ,
    LINE_LOOP = GL_LINE_LOOP ,
    POINTS = GL_POINTS ,
  };

  enum ShaderType {
    VERTEX_SHADER = GL_VERTEX_SHADER ,
    FRAGMENT_SHADER = GL_FRAGMENT_SHADER ,
    GEOMETRY_SHADER = GL_GEOMETRY_SHADER ,
    TESS_CONTROL_SHADER = GL_TESS_CONTROL_SHADER ,
    TESS_EVALUATION_SHADER = GL_TESS_EVALUATION_SHADER ,
    COMPUTE_SHADER = GL_COMPUTE_SHADER ,
  };

} // namespace yockcraft

#endif // !YOCKCRAFT_RENDER_DEFINES_HPP